import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className="h-full antialiased"
      style={{ backgroundColor: "#120016" }}
    >
      <body
        className="min-h-full flex flex-col"
        style={{ backgroundColor: "#120016" }}
      >
        {children}
      </body>
    </html>
  );
}
